# Generated by Django 3.2.5 on 2022-09-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
